### ISSUE TITLE
222 object or array ?

### ISSUE THREAD

**Issue by herrboyer** [CIEPS/json-schema-himarc#4]
https://github.com/CIEPS/json-schema-himarc/blob/b14f301a1971a2963ab74673e849ce13abeefdb5/src/field-222.schema.json#L4

222 est répétable, mais de type `object`, ça ne devrait pas plutôt être un array (c'était le cas en 1.0.6 je crois)

**Comment by rmeja** [comment]
Le profil ISSN me confirme bien que cette zone est non répétable.

**Comment by herrboyer** [comment]
ok merci !
